name: VDT
channels:
  - defaults
dependencies:
  - python=3.6
  - tensorflow
  - cython
  - pylint
  - pandas
  - pip:
    - libarchive-c==2.8
    - lief==0.9.0
    - msgpack==0.5.6
    - tables==3.4.4
    - opencv-python
    - "git+https://github.com/ppwwyyxx/tensorpack.git#egg=tensorpack"
    - "git+https://github.com/ildoonet/tf-pose-estimation.git#egg=tf-pose"

#- "git+https://github.com/thtrieu/darkflow.git#egg=darkflow"